### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by 3l3phant** [osxpeppermint/peppermint#23]
(I think these are issues but not sure so wasn't sure  if I should post as multiple ones. Sorry if I should have)
1) There's no paste into console
3) It looks like no component of the window has focus on launch (i.e. the console or editor area)
4) There's no prompt on cmd-n that you're about to lose whatever is in the editor)
5) There's no cmd-w option to close the window

**Comment by 3l3phant** [comment]
Re: No. 1 - If you copy from the editor area and paste into the console it works. If you copy from some place and then accidentally hit cmd-c in the console again (i.e. a second copy action) then it clears the clipboard of the first copy and replaces it with null.

**Comment by osxpeppermint** [comment]
Well, going through your points:

- Copy-Pasting from the Console is working up to 1.4. I guess I'll have to update it for 1.5 as well.
- Re: focus, you mean when you select/open a file from Workspace, right?
- Re: <kbd>⌘N</kbd>, you mean when adding a new file? That sounds serious...
- Re: <kbd>⌘W</kbd> I'll have a look into it

**Comment by 3l3phant** [comment]
Re: The last three - yup :)

**Comment by osxpeppermint** [comment]
Yet another clarification: are the last 3 for 1.5?

P.S. I understand 1.4 is the latest "official" release, however I'm currently working 100% on 1.5 (still in beta), which as soon as I consider "stable" enough will be the main running release. That's why I generally seem a bit confused and need to know which exact version a particulal issue refers to. :)

**Comment by osxpeppermint** [comment]
As for copy-pasting (<kbd>⌘C</kbd> and <kbd>⌘V</kbd> respectively), the issue has just been fixed for 1.5 - and will be included in the very next beta.

**Comment by 3l3phant** [comment]
Sorry about that - Yup, all of the reports are 1.4. I didn't realize 1.5b was out. Is it available on the site? Want to close out the tickets I opened and I'll retest with the new version?

**Comment by osxpeppermint** [comment]
> Sorry about that - Yup, all of the reports are 1.4. I didn't realize 1.5b was out. Is it available on the site? 

Well, yes it is :) http://osxpeppermint.com/category/blog (Just click on any of the latest blog posts and you'll find the download link). I just decided not to make 1.4 updateable to 1.5 yet (until it's stable enough). The betas (from the 2nd one and on) *are* updateable though, so you'll instantly get notified once the next one is available.

> Want to close out the tickets I opened and I'll retest with the new version?

Not really. However, since 1.5 is the version going to replace 1.4, once I "officially" release it, issues that are mentioned and already fixed in the new release, I will mark them as closed myself. :)

**Comment by osxpeppermint** [comment]
All fixed as of 1.5 Beta 7.
