### ISSUE TITLE
Import error message

### ISSUE THREAD

**Issue by 3l3phant** [osxpeppermint/peppermint#34]
After opening a new file (and so replacing the previously one because of the tab issue) if you try and reopen the same file afterward you receive an error message saying the file has already been imported. However the file isn't accessible either via the tab bar or the "Next Document" or "Previous Document" Window menu (they're grayed out).

**Comment by osxpeppermint** [comment]
First of all, items (files/folders) already in the Workspace (the sidebar / file manager on the left) have to be "unique" or imported just once - it wouldn't make much sense to have two separate instances of the very same document, anyway, would it?.

Now, the document navigation (from the Window menu) mainly works by selecting the previous/next document (if there is one - otherwise, the corresponding option would be grayed out) either in the workspace or in the tab bar.

I'm not really understanding what went wrong here. Could you please elaborate a bit?

**Comment by osxpeppermint** [comment]
Clarification: is this for the beta (1.5) or 1.4?

**Comment by 3l3phant** [comment]
1.4. Looks like the issue was user-generated. I keep the file sidebar closed to give me more space. Didn't realize the app was keeping track of the files after they were closed via the sidebar.
