### ISSUE TITLE
Feature Request: Indication of Edit Status

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#36]
There should be some way to see that a file has been edited, but not saved. Maybe a symbol on the file tab?

**Comment by rcrooks** [comment]
A large +1 on this request!

On Tuesday, January 6, 2015, Bob Rockefeller <notifications@github.com>
wrote:
> There should be some way to see that a file has been edited, but not
saved. Maybe a symbol on the file tab?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/P6ivu8t28yYuZgBIJFTgHe11HOSdoEZXOarW1NEtaHN6zR9HviAeVcfRxZbEvvcusOjArgTNZwUoD3ZNYf0TsnSc0QgV4Ken6eZYKxTOqchDkCziM13AgjkQ08PozrDX3SdncQ2eMevANGBM0zzOWwl7qwOzBg=s0-d-e1-ft#https://github.com/notifications/beacon/AAl0YRQf_KXRBS5bb4WC_f8EJGytEvkHks5ne-wVgaJpZM4DO5IP.gif
>

-- 
Robert Crooks
Director of Learning Services | P: 617 245 5090 | M: 617-584 6128
Brightcove Inc <http://www.brightcove.com/>

**Comment by osxpeppermint** [comment]
Well, up to 1.4, edited documents appeared with a blurred/grayed-out icon in the workspace. In 1.5, since the overall design has moved to a more tab-oriented concept, the indication is currently in the tab itself (the edited documents appears with their tab title in *italics*), nope? (I guess, it wasn't that obvious? :-) )

![edited](https://cloud.githubusercontent.com/assets/9476915/5631010/b05091b2-95cb-11e4-9613-44aeee174901.png)

In any case, I'm open to suggestions! :)

**Comment by bobrocke** [comment]
I didn't notice! Now that I know, that will work.

**Comment by rcrooks** [comment]
I didn’t either — that works fine for me

On Tuesday, January 6, 2015, Bob Rockefeller <notifications@github.com>
wrote:
> I didn't notice! Now that I know, that will work.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/Ejz-LTuqjNm2waWg9hBZpcIcwNMN3TcIGPvzjFyk8Acy9J5D2QdaKhzAYULH5b1sp2ASPrNfDRQ7El8YTQ7I080N2J-c1Q_3WEeoFvMFN0LOemu2W5Gs_5h7avjh7yWYH9CFSldT5WTOojavz0eoaBNdnpSR_w=s0-d-e1-ft#https://github.com/notifications/beacon/AAl0YT1ad_Fyb6Wf6EJWBpRibKtjg10Zks5ne_26gaJpZM4DO5IP.gif
>

-- 
Robert Crooks
Director of Learning Services | P: 617 245 5090 | M: 617-584 6128
Brightcove Inc <http://www.brightcove.com/>
