### ISSUE TITLE
Creating and Editing Language Grammars

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#44]
Are there language grammars in Peppermint that can be edited or created? Where and how?

**Comment by osxpeppermint** [comment]
Well, as of yet, you can neither edit nor create a new grammar. Well, you can - but not in any way I mean. It's definitely being planned. However, given the complexity it might be one of the last tweakable elements (aside from snippets/themes/etc) to make it to an official release.

What can be done though, with a varying of success, is to convert an existing TextMate/Sublime grammar to a valid Peppermint grammar. That *is* possible - given than all of them share a somewhat same model of approaching language grammars.

**Comment by bobrocke** [comment]
So, does Peppermint take a TextMate grammar and convert it to another format? Or does it use it as is? Where does it put them? Could they be editing there?

**Comment by osxpeppermint** [comment]
With a delay of some... months (apologies!!!):

Peppermint, in its very core, is based on Ace (an editor component based on Javascript). Now, regarding TextMate grammar compatibility, what *is* theoretically doable is to convert it to an Ace- (and thus Peppermint-) capable grammar. However, given that JavaScript does not support a few RegEx features (most importantly negative lookaheads, etc), if the original template does make use of them, an alternative way to express the same thing has to be found - otherwise, the original grammar *will* be converted but with missing features.

For now, given the complexity of it all, I've decided it to keep grammar development for in-house use only and give some priority to themes, snippets, etc (as for what the user can edit-tweak-add himself, I mean). So, I may consider adding some similar option for grammars as well (or perhaps an... auto-converter tool for users to play with), but at some later point.
