### ISSUE TITLE
Show the beta version

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#64]
When I check Peppermint's About dialog, I can only se the build number, not the beta version. v15.b16 might be nice.

**Comment by osxpeppermint** [comment]
Well, given that the betas are not something "official", I didn't consider it that important. That's why I keep focusing on the "Build Number" (which I mainly use for versioning). And given that - hopefully! - there aren't going to be many more betas before the release, I don't think it's such a crucial thing. I could do it, I just don't see the point... since all this is the temporary step before the usual Peppermint version system.
