### ISSUE TITLE
Interface ideas

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#70]
Right now I am oscillating between Atom and Brackets as my go-to editor. Each has strengths and irritating weaknesses. Here's what my workspace in Brackets looks like as an example of how I'm working:

![bob-colors less www br dev brackets](https://cloud.githubusercontent.com/assets/2962426/8267168/d133ec7e-1723-11e5-8c40-2772b5907208.jpg)

Brackets doesn't allow multiple windows yet, either (a pain). But it does have split screen and allows UI theming. As I follow along with Peppermint development, for me, this is the level of interface development that would put Peppermint in the running with Brackets and Atom.

And that's some of what I referred to in a different thread;  Brackets and Atom have whole companies behind them!

**Comment by osxpeppermint** [comment]
Well, splitting the view and having basically two editor views side-by-side is something that I have considered - and to be perfectly honest, it's not that difficult to implement. (I guess it goes under the category of things I have postponed until more urgent ones are resolved).

What I mostly worry about is not to make a mess with the Tabs part (I mean, will every view has its own tab bar? If not, clicking on a tab item, where should it be opening? Are the tab items to be drag'n'droppable between the two views?) and last but not least, the active view (Meaning: lots of things will have to change in order to take into account where they will perform a specific action.)

Anyway, maybe you're right and I have to push it a bit about in my priorities list...

**Comment by bobrocke** [comment]
The tabs part is a more difficult design decision. Brackets doesn't have tabs, going with the active files in the upper right. You can drag files from view to view there.

Atom uses tabs at the top and you can drag them from view to view or even window to window.

My opinion is split. Sometimes I like tabs at the top (Atom, Sublime Text, TextMate) sometimes I like them in the tree view area (Brackets, BBEdit). If I have a few files open, I like tabs at the top. But for lots of files, that doesn't work well.

Peppermint is using tabs at the top now, with a drop-down menu to select among them. Perhaps that's the best combination of the two and IMHO you should keep going that way and see if it turns out to be the best way in the end. Split the view (or allow multiple windows, or best - both) and let the tabs take care of them selves as they do now.

**Comment by osxpeppermint** [comment]
Closed as a duplicated of https://github.com/osxpeppermint/peppermint/issues/85 & https://github.com/osxpeppermint/peppermint/issues/86
