### ISSUE TITLE
Search panel close button

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#80]
Probably a lower priority feature, but it might be easy. Add a close button to the search panel in addition to the View > Search Panel menu item.

**Comment by osxpeppermint** [comment]
Well, another great suggestion.
I've been thinking of that too.

However, since the Search feature is the one that currently undergoes the most... extreme (core) facelift, I decided to postpone it. Search *does* work quite ok, but until I iron out several issues that bother me (e.g. Regex search-replace not working as it should, matches list, and other little or not-so-little things), I think it'll have to wait...

**Comment by osxpeppermint** [comment]
Close button added, as of the upcoming 1.5 beta 19.

P.S. The rest of the... facelift is a work in progress. But a lot of improvements have already been made.
