### ISSUE TITLE
Tools>Extensions disabled with no open files

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#92]
With no open files, the Tools>Extensions commands are deactivated. I think you should be able to create a theme even if no file is currently open.

**Comment by osxpeppermint** [comment]
Oops... this is another great little catch (have noticed it myself too and it's in my to-do list).

**Comment by osxpeppermint** [comment]
OK, so here's how it was solved (and it may change in the future to cover even more cases):

- all plugins are considered by default "document-based" -- meaning: they can work only if a document is open. so there is no point in having the option to execute it, unless we have a document
- now, there are plugins (like Theme Browser or Plugin Browser -- Theme Creator is a different theme, since it automatically shows the changes live, so a document *has* to be open) that do not necessarily work on a document. For these plugins, we just set an `association` -> `none` to their `info.json`.

* In the future, I'm thinking of applying it in other ways as well (e.g. project-based plugins, etc).

So... I'm marking this as closed, as of the upcoming 1.5 beta 21.
